export const products = [
	{
		id: 1,
		imageUrl: {
			small: '/images/product2.png',
			large: '/images/product2@2x.png',
		},
		description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		price: 9.999,
		discount: true,
		discount_price: 9.999,
		discount_percent: 50,
		rate: 4.2,
		pickup_place: 'Genena Mall',
		rates: 12,
	},
	{
		id: 2,
		imageUrl: {
			small: '/images/product3.png',
			large: '/images/product3@2x.png',
		},
		description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		price: 9.999,
		discount: false,
		discount_price: 9.999,
		discount_percent: 0,
		rate: 4.2,
		pickup_place: 'Genena Mall',
		pickup_info: {
			from: 'UK',
			countery: 'Egypt',
			delivery_in: 10,
		},
		rates: 5,
	},
	{
		id: 3,
		imageUrl: {
			small: '/images/product4.png',
			large: '/images/product4@2x.png',
		},
		description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		price: 9.999,
		discount: true,
		discount_price: 9.999,
		discount_percent: 70,
		rate: 4.2,
		pickup_place: 'Genena Mall',
		rates: 9,
	},
	{
		id: 4,
		imageUrl: {
			small: '/images/product5.png',
			large: '/images/product5@2x.png',
		},
		description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		price: 9.999,
		discount: true,
		discount_price: 9.999,
		discount_percent: 30,
		rate: 4.2,
		pickup_place: 'Genena Mall',
		pickup_info: {
			from: 'Egypt',
			countery: 'Egypt',
			delivery_in: 2,
		},
		rates: 19,
	},
	{
		id: 4,
		imageUrl: {
			small: '/images/product1.png',
			large: '/images/product1@2x.png',
		},
		description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		price: 9.999,
		discount: true,
		discount_price: 9.999,
		discount_percent: 30,
		rate: 4.2,
		pickup_place: 'Genena Mall',
		rates: 22,
	},
];
